[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"

  for = "/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff2"
  
  for = "/*.otf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-opentype"